name: GitHub Actions test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get Points
        id: getPoints
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://api.juejin.cn/growth_api/v1/get_cur_point?aid=${{ secrets.AID }}&uuid=${{ secrets.UUID }}"
          method: 'GET'
          customHeaders: '{ "cookie": "${{ secrets.COOKIE }}" }'
      - name: show response
        run: echo ${{ steps.getPoints.response }}