name: GitHub Actions test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get Points
        id: first_step
        run: |
          CODE=`curl "https://api.juejin.cn/growth_api/v1/check_in?aid=${{ secrets.AID }}&uuid=${{ secrets.UUID }}&_signature=${{ secrets.SIGNATURE }}" -H 'cookie:${{ secrets.COOKIE }}' --data-raw '{}'`
          echo $CODE
          err_no=`echo $CODE | sed 's/,/\n/g' | grep "err_no" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'`
          echo "::set-output name=err_no::$err_no"
      - name: step2
        if: ${{ steps.first_step.outputs.err_no != 0 }}
        run: |
          echo "FAILURE send email"
          echo ${{ steps.first_step.outputs.err_no }}
      - name: step3
        if: ${{ steps.first_step.outputs.err_no == 0 }}
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          subject: sign failed
          body: sign failed, please update the cookies
          to: ${{ secrets.USERNAME }}
          from: Github Actions