name: GitHub Actions test
on: [push]
  # schedule:
  #   - cron: 0 8 * * *
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check In
        id: first_step
        run: |
          RES=`curl "https://api.juejin.cn/growth_api/v1/check_in?aid=${{ secrets.AID }}&uuid=${{ secrets.UUID }}&_signature=${{ secrets.SIGNATURE }}" -H 'cookie:${{ secrets.COOKIE }}' --data-raw '{}'`
          echo $RES
          err_no=`echo $RES | sed 's/,/\n/g' | grep "err_no" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'`
          echo "::set-output name=err_no::$err_no"
          echo "::set-output name=response::$RES"
      - name: Send Email
        if: ${{ steps.first_step.outputs.err_no != 0 }}
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          subject: sign failed
          body: sign failed, please update the cookies or signature, response is ${{ steps.first_step.outputs.response }}
          to: ${{ secrets.USERNAME }}
          from: Github Actions
      - name: Success
        if: ${{ steps.first_step.outputs.err_no == 0 }}
        run: |
          echo "签到成功"
          echo ${{ steps.first_step.outputs.err_no }}
