name: GitHub Actions test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get Points
        run: |
          CODE=`curl "https://api.juejin.cn/growth_api/v1/get_cur_point?aid=${{ secrets.AID }}&uuid=${{ secrets.UUID }}" -H 'cookie:${{ secrets.COOKIE }}'`
        run: |
          echo $CODE