name: GitHub Actions test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get Points
        id: first_step
        run: |
          CODE=`curl "https://api.juejin.cn/growth_api/v1/get_cur_point?aid=${{ secrets.AID }}&uuid=${{ secrets.UUID }}" -H 'cookie:${{ secrets.COOKIE }}'`
          err_no=`echo $CODE | sed 's/,/\n/g' | grep "err_no" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'`
          echo "::set-output name=err_no::$err_no"
      - name: step2
        if: ${{ steps.first_step.outputs.err_no }} != "0"
        run: |
          echo "FAILURE send email"
          echo ${{ steps.first_step.outputs.err_no }}
      - name: step3
        if: steps.first_step.outputs.err_no == "0"
          echo "SUCCESS"